-- Auto ELT Metadata Guard 가 사용하는 메타데이터 스키마 초기 설정
-- 최초 1회 ACCOUNTADMIN 또는 권한 있는 role 로 실행

CREATE SCHEMA IF NOT EXISTS META_GUARD;

-- 격리(quarantine)된 소스 테이블 목록. dbt 의 no_blocked_source 테스트가 이 테이블을 참조하여
-- 격리 상태인 소스에 의존하는 모델의 빌드를 자동으로 실패시킴.
CREATE TABLE IF NOT EXISTS META_GUARD.BLOCKED_SOURCES (
    TABLE_FQN   STRING,
    REASON      STRING,
    BLOCKED_AT  TIMESTAMP_NTZ,
    IS_ACTIVE   BOOLEAN
);

-- 행수 이력 (전일 대비 이상치 탐지용)
CREATE TABLE IF NOT EXISTS META_GUARD.ROW_COUNT_HISTORY (
    TABLE_FQN   STRING,
    ROW_COUNT   NUMBER,
    CHECKED_AT  TIMESTAMP_NTZ
);

-- 컬럼별 NULL 비율 이력 (전일 대비 급증 탐지용)
CREATE TABLE IF NOT EXISTS META_GUARD.NULL_RATE_HISTORY (
    TABLE_FQN    STRING,
    COLUMN_NAME  STRING,
    NULL_RATE    FLOAT,
    CHECKED_AT   TIMESTAMP_NTZ
);

-- (참고) Python 서비스 계정에 필요한 최소 권한 예시
-- GRANT USAGE ON DATABASE ANALYTICS TO ROLE TRANSFORMER;
-- GRANT USAGE ON SCHEMA META_GUARD TO ROLE TRANSFORMER;
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA META_GUARD TO ROLE TRANSFORMER;
-- GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE TRANSFORMER; -- ACCOUNT_USAGE 조회용
